### ISSUE TITLE
Running detection_img_tf2.py [...] resulting in AttributeError: ... 'cv2' has no attribute

### ISSUE THREAD

**Issue by StormWeaver** [AlvaroCavalcante/auto_annotate#42]
I currently have installed TF2 via the instructions on this [git repo](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2.md) using the docker options and have run the Object Detection test code mentioned in this [issue](https://github.com/AlvaroCavalcante/auto_annotate/issues/28#issuecomment-903314788). After placing the desired files from the Auto_Annotate script folder and running the referenced TF2 python command, 

`python3 scripts/detection_img_tf2.py --saved_model /path-saved-model --labelmap /path-label-map.pbtxt --imgs /path-of-the-imgs`

I receive the following set of errors.

```
C:\Users\name\Downloads\auto_annotate-master\auto_annotate-master>python3 scripts/detection_img_tf2.py --saved_model /path-saved-model --labelmap /path-label-map.pbtxt --imgs /path-of-the-imgs
Traceback (most recent call last):
  File "C:\Users\name\Downloads\auto_annotate-master\auto_annotate-master\scripts\detection_img_tf2.py", line 5, in <module>
    import cv2
  File "C:\Users\name\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\cv2\__init__.py", line 181, in <module>
    bootstrap()
  File "C:\Users\name\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\cv2\__init__.py", line 175, in bootstrap
    if __load_extra_py_code_for_module("cv2", submodule, DEBUG):
  File "C:\Users\name\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\cv2\__init__.py", line 28, in __load_extra_py_code_for_module
    py_module = importlib.import_module(module_name)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\name\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\cv2\gapi\__init__.py", line 290, in <module>
    cv.gapi.wip.GStreamerPipeline = cv.gapi_wip_gst_GStreamerPipeline
AttributeError: partially initialized module 'cv2' has no attribute 'gapi_wip_gst_GStreamerPipeline' (most likely due to a circular import)
```
Is the command above supposed to be modified with custom paths entered in these sections? /path-saved-model  /path-label /path-of-the-imgs?

**Comment by AlvaroCavalcante** [comment]
I'm closing this issue due to inactivity! If you need more help, please, open this again!
