### ISSUE TITLE
tensorflow.python.framework.errors_impl.NotFoundError: /path-label-map.pbtxt; No such file or directory

### ISSUE THREAD

**Issue by advaitgupta** [AlvaroCavalcante/auto_annotate#44]
Traceback (most recent call last):
  File "/Users/advaitgupta/auto_annotate/scripts/detection_img_tf2.py", line 51, in <module>
    category_index = label_map_util.create_category_index_from_labelmap(args.labelmap,
  File "/Users/advaitgupta/Tensorflow/tf2_api_env/lib/python3.9/site-packages/object_detection/utils/label_map_util.py", line 360, in create_category_index_from_labelmap
    categories = create_categories_from_labelmap(label_map_path, use_display_name)
  File "/Users/advaitgupta/Tensorflow/tf2_api_env/lib/python3.9/site-packages/object_detection/utils/label_map_util.py", line 340, in create_categories_from_labelmap
    label_map = load_labelmap(label_map_path)
  File "/Users/advaitgupta/Tensorflow/tf2_api_env/lib/python3.9/site-packages/object_detection/utils/label_map_util.py", line 168, in load_labelmap
    label_map_string = fid.read()
  File "/Users/advaitgupta/Tensorflow/tf2_api_env/lib/python3.9/site-packages/tensorflow/python/lib/io/file_io.py", line 114, in read
    self._preread_check()
  File "/Users/advaitgupta/Tensorflow/tf2_api_env/lib/python3.9/site-packages/tensorflow/python/lib/io/file_io.py", line 76, in _preread_check
    self._read_buf = _pywrap_file_io.BufferedInputStream(
tensorflow.python.framework.errors_impl.NotFoundError: /path-label-map.pbtxt; No such file or directory

**Comment by AlvaroCavalcante** [comment]
Hello @advaitgupta, thank you for trying to use the project, what command did you use to run the auto annotation process? Remember that the "/path-label-map.pbtxt" is a command variable that you need to provide with your own label map path. Similarly, you need to give the path of your saved model and your images. The running command would be something like this:
``` python3 scripts/detection_img_tf2.py --saved_model /home/desktop/saved_model --labelmap /home/desktop/label_map.pbtxt --imgs /home/deskotop/my_images ```.

**Comment by AlvaroCavalcante** [comment]
I'm closing this issue due to inactivity! If you need more help, please, open this again!
